# Configuration for jet flavor tagging pipeline

# Jet flavor mapping: maps file patterns to jet flavor labels
# Example: if filename contains "Zbb" -> creates branch "recojet_isB" with value 1 for that sample
flavor_mapping:
  Zuu: recojet_isUDS
  Zdd: recojet_isUDS
  Zss: recojet_isUDS
  Zcc: recojet_isC
  Zbb: recojet_isB
  Znn: recojet_isN

# Jet-level variables (vector of floats per event)
# Each entry is a list of values, one per jet in the event
jet_variables:
  - jet_mass
  - jet_p
  - jet_e
  - jet_phi
  - jet_theta
  - jet_pT
  - jet_nnhad
  - jet_ngamma
  - jet_nchad
  - jet_nel
  - jet_nmu
  - jet_nconst

# Particle Flow Candidate (PFCand) level variables
# Each entry is a list of lists: [[jet1_constituents], [jet2_constituents], ...]
# NaN/None values will be converted to 0.0
pfcand_variables:
  # Particle identification
  - pfcand_isMu
  - pfcand_isEl
  - pfcand_isChargedHad
  - pfcand_isGamma
  - pfcand_isNeutralHad
  
  # Basic kinematics
  - pfcand_e
  - pfcand_p
  - pfcand_theta
  - pfcand_phi
  - pfcand_charge
  - pfcand_type
  
  # Relative kinematic variables
  - pfcand_erel
  - pfcand_erel_log
  - pfcand_thetarel
  - pfcand_phirel
  
  # Impact parameters
  - pfcand_dxy
  - pfcand_dz
  - pfcand_phi0
  - pfcand_C
  - pfcand_ct
  
  # Track covariance matrix elements
  - pfcand_dptdpt
  - pfcand_dxydxy
  - pfcand_dzdz
  - pfcand_dphidphi
  - pfcand_detadeta
  - pfcand_dxydz
  - pfcand_dphidxy
  - pfcand_phidz
  - pfcand_phictgtheta
  - pfcand_dxyctgtheta
  - pfcand_dlambdadz
  - pfcand_cctgtheta
  - pfcand_phic
  - pfcand_dxyc
  - pfcand_cdz
  
  # B-tagging variables
  - pfcand_btagSip2dVal
  - pfcand_btagSip2dSig
  - pfcand_btagSip3dVal
  - pfcand_btagSip3dSig
  - pfcand_btagJetDistVal
  - pfcand_btagJetDistSig
  
  # dE/dx variables - pads
  - pfcand_dEdx_pads_type
  - pfcand_dEdx_pads_value
  - pfcand_dEdx_pads_error
  
  # PID p-values - pads
  - pfcand_PID_pval_pads_ele
  - pfcand_PID_pval_pads_mu
  - pfcand_PID_pval_pads_pi
  - pfcand_PID_pval_pads_kaon
  - pfcand_PID_pval_pads_proton
  
  # dE/dx variables - wires
  - pfcand_dEdx_wires_type
  - pfcand_dEdx_wires_value
  - pfcand_dEdx_wires_error
  
  # PID p-values - wires
  - pfcand_PID_pval_wires_ele
  - pfcand_PID_pval_wires_mu
  - pfcand_PID_pval_wires_pi
  - pfcand_PID_pval_wires_kaon
  - pfcand_PID_pval_wires_proton

# Input tree name
input_tree_name: events

# Output tree name
output_tree_name: tree
